export const UPDATE_USER_LISTS = 'UPDATE_USER_LISTS'

export const FETCH_RECIPES_PENDING = 'FETCH_RECIPES_PENDING'
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS'
export const FETCH_RECIPES_ERROR = 'FETCH_RECIPES_ERROR'

export const FETCH_RECIPES_DETAILS_PENDING = 'FETCH_RECIPES_DETAILS_PENDING'
export const FETCH_RECIPES_DETAILS_SUCCESS = 'FETCH_RECIPES_DETAILS_SUCCESS'
export const REMOVE_RECIPES_DETAILS = 'REMOVE_RECIPES_DETAILS'

export const FETCH_SHOPPINGLIST_PENDING = 'FETCH_SHOPPINGLIST_PENDING'
export const FETCH_SHOPPINGLIST_SUCCESS = 'FETCH_SHOPPINGLIST_SUCCESS'
export const FETCH_SHOPPINGLIST_ERROR = 'FETCH_SHOPPINGLIST_ERROR'

export const FETCH_FRIDGE_PENDING = 'FETCH_FRIDGE_PENDING'
export const FETCH_FRIDGE_SUCCESS = 'FETCH_FRIDGE_SUCCESS'
export const FETCH_FRIDGE_ERROR = 'FETCH_FRIDGE_ERROR'