export const GET_RECIPES = 'GET_RECIPES'
export const ADD_RECIPES = 'ADD_RECIPES'
export const REMOVE_RECIPES = 'REMOVE_RECIPES'

export const GET_SHOPPINGLIST = 'GET_SHOPPINGLIST'
export const ADD_ITEMS_TO_SHOPPINGLIST = 'ADD_ITEMS_TO_SHOPPINGLIST'
export const REMOVE_ITEMS_FROM_SHOPPINGLIST = 'REMOVE_ITEMS_FROM_SHOPPINGLIST'

export const GET_FRIDGE = 'GET_FRIDGE'
export const ADD_ITEMS_TO_FRIDGE = 'ADD_ITEMS_TO_FRIDGE'
export const REMOVE_ITEMS_FROM_FRIDGE = 'REMOVE_ITEMS_FROM_FRIDGE'

export const REQUEST_PENDING = 'REQUEST_PENDING'
export const REQUEST_ERROR = 'REQUEST_ERROR'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'