export const UPDATE_USER_LISTS = 'UPDATE_USER_LISTS'

export const FETCH_RECIPES_PENDING = 'FETCH_RECIPES_PENDING'
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS'
export const FETCH_RECIPES_ERROR = 'FETCH_RECIPES_ERROR'

export const ADD_RECIPES = 'ADD_RECIPES'
export const REMOVE_RECIPES = 'REMOVE_RECIPES'

export const FETCH_SHOPPINGLIST = 'FETCH_SHOPPINGLIST'
export const ADD_ITEMS_TO_SHOPPINGLIST = 'ADD_ITEMS_TO_SHOPPINGLIST'
export const REMOVE_ITEMS_FROM_SHOPPINGLIST = 'REMOVE_ITEMS_FROM_SHOPPINGLIST'

export const FETCH_FRIDGE = 'FETCH_FRIDGE'
export const ADD_ITEMS_TO_FRIDGE = 'ADD_ITEMS_TO_FRIDGE'
export const REMOVE_ITEMS_FROM_FRIDGE = 'REMOVE_ITEMS_FROM_FRIDGE'

export const REQUEST_PENDING = 'REQUEST_PENDING'
export const REQUEST_ERROR = 'REQUEST_ERROR'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'